# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  nginx:
    repository: sptit145/reverse-proxy-nginx
    tag: 0.0.1
    pullPolicy: IfNotPresent
  squid:
    repository: sptit145/reverse-proxy-squid
    tag: 0.0.1
    pullPolicy: IfNotPresent
  icap:
    repository: sptit145/reverse-proxy-c-icap
    tag: 0.0.1
    pullPolicy: IfNotPresent
podAnnotations: {}
application:
  nginx:
    secretName: reverse-proxy-nginx
    env:
      ALLOWED_DOMAINS: bsigroup.com.glasswall-icap.com,www.bsigroup.com.glasswall-icap.com,page.bsigroup.com.glasswall-icap.com
      ROOT_DOMAIN: glasswall-icap.com
      SUBFILTER_ENV: ".bsigroup.com,.bsigroup.com.glasswall-icap.com"
      #ICAP_URL: "icap://54.155.107.189:1344/gw_rebuild"
      ICAP_URL: "icap://3.129.78.231:1344/gw_rebuild"
    secrets: {}
  squid:
    secretName: reverse-proxy-squid
    env:
      ALLOWED_DOMAINS: bsigroup.com.glasswall-icap.com,www.bsigroup.com.glasswall-icap.com,page.bsigroup.com.glasswall-icap.com
      ROOT_DOMAIN: glasswall-icap.com
      #ICAP_URL: "icap://54.155.107.189:1344/gw_rebuild"
      ICAP_URL: "icap://3.129.78.231:1344/gw_rebuild"
    secrets: {}
  icap:
    secretName: reverse-proxy-icap
    env: {}
    secrets: {}

service:
  nginx:
    enabled: true
    annotations: {}
    name: nginx
    type: ClusterIP
    additionalHosts:
    - www.bsigroup.com.glasswall-icap.com
    - page.bsigroup.com.glasswall-icap.com
    externalPort: 443
    internalPort: 443
    url: bsigroup.com.glasswall-icap.com
  squid:
    enabled: true
    annotations: {}
    name: squid
    type: ClusterIP
    additionalHosts:
    commonName:
    externalPort: 8080
    internalPort: 8080
  icap:
    enabled: true
    annotations: {}
    name: icap
    type: ClusterIP
    additionalHosts:
    externalPort: 1344
    internalPort: 1344
ingress:
  enabled: true
  tls:
    secretName: echo-tls
    enabled: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    kubernetes.io/ingress.class: "nginx"
  path: /
livenessProbe:
  path: "/"
  initialDelaySeconds: 30
  timeoutSeconds: 3
  scheme: "HTTP"
readinessProbe:
  path: "/"
  initialDelaySeconds: 30
  timeoutSeconds: 3
  scheme: "HTTP"

resources:
  nginx:
    limits:
      cpu: 250m
      memory: 250Mi
    requests:
      cpu: 250m
      memory: 250Mi
  squid:
    limits:
      cpu: 250m
      memory: 500Mi
    requests:
      cpu: 250m
      memory: 500Mi
  icap:
    limits:
      cpu: 250m
      memory: 500Mi
    requests:
      cpu: 250m
      memory: 500Mi

#
podDisruptionBudget:
  enabled: false
  # minAvailable: 1
  maxUnavailable: 1
scale:
  nginx:
    enabled: false
    MinReplicaCount: 1
    MaxReplicaCount: 2
  squid:
    enabled: false
    MinReplicaCount: 1
    MaxReplicaCount: 2
  icap:
    enabled: false
    MinReplicaCount: 1
    MaxReplicaCount: 2
